# Generated by Django 3.0.8 on 2020-08-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password2',
        ),
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
