# Generated by Django 3.0.8 on 2020-09-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200901_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
